@startuml

enum AzureRDBTiers{
BASIC
STANDARD
PREMIUM
}

class AzureRDBTierThresholds{
+ long dtuMax
+ long storageMax
}

class AzureRDBTierWithPrice{
+ AzureRdbTier tier;
+ Double costPerDtu;
}

class AzureMultiDimensionsRDBTiers{
- private Map<AzureRDBTiers, AzureRDBTierThresholds> tiersThresholdMap;
- private PriorityQueue<AzureRDBTierWithPrice> tiersSortedByPrice;
- private Map<AzureRDBTiers, PriorityQueue<Long>> dtuOptions;
- private Map<AzureRDBTiers, PriorityQueue<Long>> storageOptions;
--
- void initializeTiers()
- boolean canSatisfyBothDemands()
+ AzureRdbTier findMinTier()
+ Optional<Long> getDesiredDtuDemand(){
+ Optional<Long> getDesiredStorageDemand()
}

AzureMultiDimensionsRDBTiers *-left AzureRDBTierThresholds
AzureMultiDimensionsRDBTiers *- AzureRDBTierWithPrice
AzureRDBTierWithPrice *- AzureRDBTiers

@enduml